/*
 * This file is generated by jOOQ.
 */
package pdv.l3ug1m.github.com.pdvservice.jooq;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.impl.Internal;

import pdv.l3ug1m.github.com.pdvservice.jooq.tables.Pdvs;
import pdv.l3ug1m.github.com.pdvservice.jooq.tables.records.PdvsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PdvsRecord, Long> IDENTITY_PDVS = Identities0.IDENTITY_PDVS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<PdvsRecord, Long> IDENTITY_PDVS = Internal.createIdentity(Pdvs.PDVS, Pdvs.PDVS.ID_PDVS);
    }
}
