/*
 * This file is generated by jOOQ.
 */
package pdv.l3ug1m.github.com.pdvservice.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.pdvs_id_pdvs_seq</code>
     */
    public static final Sequence<Long> PDVS_ID_PDVS_SEQ = new SequenceImpl<Long>("pdvs_id_pdvs_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
