/*
 * This file is generated by jOOQ.
 */
package pdv.l3ug1m.github.com.pdvservice.jooq;


import javax.annotation.Generated;

import pdv.l3ug1m.github.com.pdvservice.jooq.tables.Pdvs;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.pdvs</code>.
     */
    public static final Pdvs PDVS = pdv.l3ug1m.github.com.pdvservice.jooq.tables.Pdvs.PDVS;
}
