/*
 * This file is generated by jOOQ.
 */
package pdv.l3ug1m.github.com.pdvservice.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;

import pdv.l3ug1m.github.com.pdvservice.jooq.tables.Pdvs;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PdvsRecord extends TableRecordImpl<PdvsRecord> implements Record6<Long, String, String, String, String, String> {

    private static final long serialVersionUID = 2008902176;

    /**
     * Setter for <code>public.pdvs.id_pdvs</code>.
     */
    public void setIdPdvs(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pdvs.id_pdvs</code>.
     */
    public Long getIdPdvs() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pdvs.tenant</code>.
     */
    public void setTenant(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pdvs.tenant</code>.
     */
    public String getTenant() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pdvs.nome</code>.
     */
    public void setNome(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pdvs.nome</code>.
     */
    public String getNome() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.pdvs.cidade</code>.
     */
    public void setCidade(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pdvs.cidade</code>.
     */
    public String getCidade() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.pdvs.endereco</code>.
     */
    public void setEndereco(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pdvs.endereco</code>.
     */
    public String getEndereco() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.pdvs.cep</code>.
     */
    public void setCep(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pdvs.cep</code>.
     */
    public String getCep() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Pdvs.PDVS.ID_PDVS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Pdvs.PDVS.TENANT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Pdvs.PDVS.NOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Pdvs.PDVS.CIDADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Pdvs.PDVS.ENDERECO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Pdvs.PDVS.CEP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getIdPdvs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTenant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCidade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCep();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getIdPdvs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTenant();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCidade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCep();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PdvsRecord value1(Long value) {
        setIdPdvs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PdvsRecord value2(String value) {
        setTenant(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PdvsRecord value3(String value) {
        setNome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PdvsRecord value4(String value) {
        setCidade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PdvsRecord value5(String value) {
        setEndereco(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PdvsRecord value6(String value) {
        setCep(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PdvsRecord values(Long value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PdvsRecord
     */
    public PdvsRecord() {
        super(Pdvs.PDVS);
    }

    /**
     * Create a detached, initialised PdvsRecord
     */
    public PdvsRecord(Long idPdvs, String tenant, String nome, String cidade, String endereco, String cep) {
        super(Pdvs.PDVS);

        set(0, idPdvs);
        set(1, tenant);
        set(2, nome);
        set(3, cidade);
        set(4, endereco);
        set(5, cep);
    }
}
