/*
 * This file is generated by jOOQ.
 */
package pdv.l3ug1m.github.com.pdvservice.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pdvs implements Serializable {

    private static final long serialVersionUID = -1907097351;

    private Long   idPdvs;
    private String tenant;
    private String nome;
    private String cidade;
    private String endereco;
    private String cep;

    public Pdvs() {}

    public Pdvs(Pdvs value) {
        this.idPdvs = value.idPdvs;
        this.tenant = value.tenant;
        this.nome = value.nome;
        this.cidade = value.cidade;
        this.endereco = value.endereco;
        this.cep = value.cep;
    }

    public Pdvs(
        Long   idPdvs,
        String tenant,
        String nome,
        String cidade,
        String endereco,
        String cep
    ) {
        this.idPdvs = idPdvs;
        this.tenant = tenant;
        this.nome = nome;
        this.cidade = cidade;
        this.endereco = endereco;
        this.cep = cep;
    }

    public Long getIdPdvs() {
        return this.idPdvs;
    }

    public void setIdPdvs(Long idPdvs) {
        this.idPdvs = idPdvs;
    }

    public String getTenant() {
        return this.tenant;
    }

    public void setTenant(String tenant) {
        this.tenant = tenant;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    public String getEndereco() {
        return this.endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pdvs (");

        sb.append(idPdvs);
        sb.append(", ").append(tenant);
        sb.append(", ").append(nome);
        sb.append(", ").append(cidade);
        sb.append(", ").append(endereco);
        sb.append(", ").append(cep);

        sb.append(")");
        return sb.toString();
    }
}
